# Generated by Django 4.1.7 on 2023-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=250)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(choices=[('M', 'Meeting'), ('W', 'Workshop')], max_length=1)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('volunteersJob', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='event_images')),
            ],
        ),
        migrations.CreateModel(
            name='HumanitarianContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='humanitarianContainers_images')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Second name')),
                ('description', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=250)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4)),
                ('notifyMe', models.CharField(choices=[('E', 'Email'), ('P', 'Phone'), ('B', 'Both')], max_length=1, verbose_name='Notify me')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('additionalInfo', models.TextField(blank=True, null=True, verbose_name='Additional information')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Surname')),
                ('description', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=250)),
                ('location', models.CharField(max_length=200)),
                ('additionalInfo', models.TextField(blank=True, null=True, verbose_name='Additional information')),
                ('notifyMe', models.CharField(blank=True, choices=[('E', 'Email'), ('P', 'Phone'), ('B', 'Both')], max_length=1, null=True)),
                ('members', models.ManyToManyField(to='ClosetClutter.individual')),
            ],
        ),
    ]
