# Generated by Django 4.1.7 on 2023-08-14 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=250)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(choices=[('Meeting', 'Meeting'), ('Workshop', 'Workshop')], max_length=10)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('volunteersJob', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=250)),
                ('numOfMembers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('numOfMembersMale', models.PositiveIntegerField()),
                ('numOfMembersFemale', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('additionalInfo', models.TextField()),
                ('notifyMe', models.CharField(choices=[('E', 'Email'), ('P', 'Phone'), ('B', 'Both')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HumanitarianContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=250)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('size', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], max_length=2)),
                ('notifyMe', models.CharField(choices=[('E', 'Email'), ('P', 'Phone'), ('B', 'Both')], max_length=1)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClosetClutter.family')),
            ],
        ),
    ]
